[package]
name = "rust_tracking_allocator_issue"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tracking-allocator = "0.4.0"